import { StyleSheet } from 'react-native';
import { colors } from './constants';

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EDE7E3',
  },
  phone: {
    width: 375,
    height: 760,
    maxHeight: '100%',
    backgroundColor: colors.bg,
    borderRadius: 44,
    borderWidth: 1,
    borderColor: '#17140F',
    overflow: 'hidden',
    shadowColor: '#1C1A17',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.35,
    shadowRadius: 40,
    elevation: 12,
  },
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  status: {
    height: 44,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '600',
  },
  logoGlow: {
    position: 'absolute',
    top: 50,
    right: -71,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: colors.softRed,
    opacity: 0.85,
  },
  logoContainer: {
    marginTop: 5,
    marginHorizontal: 9,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeLogo: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  welcomeCopy: {
    marginTop: -12,
    paddingHorizontal: 42,
    alignItems: 'center',
  },
  eyebrowCentered: {
    color: colors.red,
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 1.1,
    textAlign: 'center',
  },
  welcomeTitle: {
    marginTop: 12,
    color: colors.ink,
    fontSize: 34,
    fontWeight: '700',
    textAlign: 'center',
  },
  centerBody: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  loginPanel: {
    marginTop: 100,
    marginHorizontal: 20,
    padding: 20,
    height: 140,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    shadowColor: '#1C1A17',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 6,
    justifyContent: 'space-between',
  },
  panelHeading: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '700',
  },
  input: {
    height: 46,
    backgroundColor: colors.bg,
    borderRadius: 16,
    paddingHorizontal: 13,
    fontSize: 13,
    color: colors.ink,
    fontWeight: '500',
  },
  pinInputHidden: {
    position: 'absolute',
    width: 0,
    height: 0,
    opacity: 0,
  },
  pinBox: {
    width: 40,
    height: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.ink,
  },
  smallBody: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 15,
  },
  header: {
    height: 70,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 12,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: 10.5,
    fontWeight: '500',
    letterSpacing: 1.05,
  },
  headerTitle: {
    marginTop: 2,
    color: colors.ink,
    fontSize: 21,
    fontWeight: '700',
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: colors.card,
    fontSize: 13,
    fontWeight: '700',
  },
  scrollBottom: {
    paddingHorizontal: 20,
    paddingBottom: 108,
  },
  sectionLabel: {
    marginTop: 12,
    marginBottom: 13,
    color: colors.muted,
    fontSize: 10.5,
    fontWeight: '500',
    letterSpacing: 1.05,
    textTransform: 'uppercase',
  },
  credentialCard: {
    height: 190,
    borderRadius: 22,
    padding: 20,
    overflow: 'hidden',
    shadowColor: '#1C1A17',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.45,
    shadowRadius: 30,
    elevation: 8,
  },
  credentialCardCompact: {
    height: 199,
    marginTop: 8,
  },
  ringOne: {
    position: 'absolute',
    top: -38,
    right: -37,
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  ringTwo: {
    position: 'absolute',
    top: -22,
    right: -21,
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
  },
  ringThree: {
    position: 'absolute',
    top: -6,
    right: -5,
    width: 86,
    height: 86,
    borderRadius: 43,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
  },
  credentialTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  auSeal: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  auSealText: {
    color: colors.card,
    fontSize: 13,
    fontWeight: '700',
  },
  activePill: {
    width: 76,
    height: 24,
    borderRadius: 100,
    backgroundColor: 'rgba(255,255,255,0.16)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  activeDot: {
    color: colors.mint,
    fontSize: 8,
    fontWeight: '700',
  },
  activeText: {
    color: colors.card,
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 1,
  },
  cardEyebrow: {
    marginTop: 18,
    color: colors.card,
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 1,
  },
  degree: {
    marginTop: 8,
    color: colors.card,
    fontSize: 19,
    fontWeight: '700',
  },
  major: {
    marginTop: 8,
    color: colors.card,
    fontSize: 12.5,
  },
  cardMetaRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardMetaRight: {
    alignItems: 'flex-end',
  },
  cardMetaLabel: {
    color: colors.card,
    fontSize: 11.5,
    opacity: 0.85,
  },
  cardMetaValue: {
    marginTop: 1,
    color: colors.card,
    fontSize: 13,
    fontWeight: '600',
  },
  summary: {
    marginTop: 32,
    height: 78,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  stat: {
    width: 76,
    alignItems: 'center',
  },
  statValue: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '700',
  },
  statLabel: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 10.5,
    fontWeight: '500',
  },
  notice: {
    height: 62,
    marginBottom: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    flexDirection: 'row',
    alignItems: 'center',
  },
  noticeIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeIconText: {
    fontSize: 15,
    fontWeight: '600',
  },
  noticeText: {
    flex: 1,
    marginLeft: 7,
  },
  noticeTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '600',
  },
  noticeSub: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 11.5,
  },
  chevron: {
    color: colors.muted,
    fontSize: 18,
    fontWeight: '600',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 78,
    borderTopWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(250,247,245,0.94)',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    paddingTop: 15,
  },
  navItem: {
    width: 80,
    alignItems: 'center',
  },
  navIcon: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: '600',
  },
  navText: {
    marginTop: 6,
    color: colors.muted,
    fontSize: 10,
    fontWeight: '600',
  },
  navActive: {
    color: colors.red,
  },
  backHeader: {
    height: 70,
    paddingHorizontal: 20,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  backArrow: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  backTitle: {
    color: colors.ink,
    fontSize: 14.5,
    fontWeight: '700',
  },
  backSub: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 11,
  },
  detailContent: {
    paddingHorizontal: 20,
    paddingBottom: 112,
    gap: 12,
  },
  infoPanel: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  infoTitle: {
    marginBottom: 12,
    color: colors.ink,
    fontSize: 12.5,
    fontWeight: '700',
  },
  infoRow: {
    minHeight: 23,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  infoKey: {
    width: 130,
    color: colors.muted,
    fontSize: 12,
  },
  infoValue: {
    flex: 1,
    color: colors.ink,
    fontSize: 11.5,
    textAlign: 'right',
    fontWeight: '500',
  },
  actionStack: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 36,
    gap: 8,
  },
  primaryButton: {
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryText: {
    color: colors.card,
    fontSize: 14,
    fontWeight: '600',
  },
  secondaryButton: {
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '600',
  },
  simpleTop: {
    height: 68,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pageTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '700',
  },
  doneText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  successHalo: {
    height: 164,
    alignItems: 'center',
    justifyContent: 'center',
  },
  haloOuter: {
    position: 'absolute',
    width: 164,
    height: 164,
    borderRadius: 82,
    backgroundColor: '#DDF7E9',
  },
  haloMiddle: {
    position: 'absolute',
    width: 116,
    height: 116,
    borderRadius: 58,
    backgroundColor: '#BDEED2',
  },
  haloCore: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  check: {
    color: colors.card,
    fontSize: 34,
    fontWeight: '800',
  },
  successTitle: {
    marginTop: 28,
    color: colors.blueInk,
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
  },
  successCopy: {
    marginTop: 8,
    marginHorizontal: 54,
    color: colors.blueMuted,
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
  },
  storedCard: {
    marginTop: 10,
    marginHorizontal: 20,
    height: 138,
    borderRadius: 22,
    backgroundColor: colors.red,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  cardLogo: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardLogoText: {
    color: colors.card,
    fontSize: 18,
    fontWeight: '800',
  },
  storedText: {
    marginLeft: 16,
    flex: 1,
  },
  storedIssuer: {
    color: colors.card,
    fontSize: 12,
    opacity: 0.85,
  },
  storedTitle: {
    marginTop: 4,
    color: colors.card,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 22,
  },
  storedDesc: {
    marginTop: 2,
    color: colors.card,
    fontSize: 12,
    opacity: 0.9,
  },
  verifiedPill: {
    position: 'absolute',
    right: 22,
    top: 58,
    width: 82,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedText: {
    color: colors.card,
    fontSize: 11,
    fontWeight: '600',
  },
  successActions: {
    marginTop: 18,
    marginHorizontal: 32,
    gap: 8,
  },
  switchRow: {
    height: 49,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  switchLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '500',
  },
  switchCode: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 10.5,
  },
  switchTrack: {
    width: 38,
    height: 22,
    borderRadius: 11,
    padding: 2,
    backgroundColor: colors.border,
  },
  switchTrackOn: {
    backgroundColor: colors.red,
  },
  switchKnob: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.card,
  },
  switchKnobOn: {
    transform: [{ translateX: 16 }],
  },
  toast: {
    height: 48,
    borderRadius: 16,
    backgroundColor: colors.red,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  toastDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.card,
    marginRight: 10,
  },
  toastText: {
    color: colors.card,
    fontSize: 12.5,
    fontWeight: '600',
  },
  validBanner: {
    height: 84,
    borderRadius: 18,
    backgroundColor: '#E5F7EC',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  validIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  validCheck: {
    color: colors.card,
    fontSize: 22,
    fontWeight: '800',
  },
  validTitle: {
    color: colors.green,
    fontSize: 16,
    fontWeight: '700',
  },
  validSub: {
    marginTop: 4,
    color: colors.green,
    fontSize: 11.5,
  },
  qr: {
    alignSelf: 'center',
    width: 120,
    height: 120,
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.card,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5.2,
  },
  qrPixel: {
    width: 7.7,
    height: 7.7,
    borderRadius: 2,
    backgroundColor: colors.card,
  },
  qrPixelOn: {
    backgroundColor: colors.ink,
  },
  qrCaption: {
    color: colors.ink,
    fontSize: 12,
    textAlign: 'center',
  },
  trustText: {
    color: colors.ink,
    fontSize: 12,
  },
  profileCard: {
    minHeight: 108,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: 18,
  },
  profileAvatar: {
    position: 'absolute',
    top: 12,
    left: 18,
    width: 46,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfo: {
    marginLeft: 58,
  },
  profileName: {
    color: colors.ink,
    fontSize: 21,
    fontWeight: '700',
  },
  profileMeta: {
    marginTop: 2,
    color: colors.muted,
    fontSize: 10.5,
  },
  schoolText: {
    marginTop: 12,
    color: colors.muted,
    fontSize: 10.5,
    lineHeight: 13,
  },
  settingRow: {
    height: 46,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '500',
  },
  logoutButton: {
    height: 46,
    marginTop: 110,
    borderRadius: 16,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutText: {
    color: colors.card,
    fontSize: 13,
    fontWeight: '700',
  },
  battery: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  batteryInner: {
    width: 20,
    height: 9,
    borderWidth: 1,
    borderColor: colors.ink,
    borderRadius: 2.5,
    padding: 1,
  },
  batteryCharge: {
    width: '70%',
    height: '100%',
    backgroundColor: colors.ink,
    borderRadius: 1,
  },
  batteryTerminal: {
    width: 1,
    height: 4,
    backgroundColor: colors.ink,
    marginLeft: 1,
  },
});
